name: C++ CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Build
        run: cmake -B build && cmake --build build
      - name: Test
        run: cd build && ctest
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: hello-binary
          path: build/hello_world
